FROM nvcr.io/nvidia/clara-holoscan/holoscan:v3.7.0-cuda12-dgpu

ARG DEBIAN_FRONTEND=noninteractive

ENV PYTHONPATH="/usr/local/lib/python3/dist-packages:${PYTHONPATH}"
ENV LD_LIBRARY_PATH="/opt/nvidia/holoscan/lib:${LD_LIBRARY_PATH}"

#
# Global Dependencies
#

RUN apt update && \
    apt install --no-install-recommends -y \
        python3-dev \
        python3-pip \
        python3-pybind11 \
        build-essential \
        pkg-config \
        cmake \
        git \
        g++-11 \
        gcc-11 \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir ninja
RUN python3 -m pip install --no-cache-dir git+https://github.com/luigifcruz/meson.git@system-includes

#
# Install ANO (transport)
#

RUN apt update && \
    apt install --no-install-recommends -y \
        build-essential \
        python3-pyelftools \
        libnuma-dev \
        && rm -rf /var/lib/apt/lists/*

RUN wget -q https://fast.dpdk.org/rel/dpdk-24.11.3.tar.xz && \
    tar xf dpdk-24.11.3.tar.xz && \
    cd dpdk-stable-24.11.3/ && \
    meson build -Dplatform=generic -Dmachine=generic && \
    ninja -C build install

RUN git clone https://github.com/luigifcruz/holoscan-networking.git && \
    cd holoscan-networking && \
    meson build && \
    cd build && \
    ninja install

#
# Install MatX (transport)
#

RUN git clone https://github.com/NVIDIA/MatX.git
RUN cd MatX && \
    git checkout ad55c6b894f0fdef65294858d9561ba31baa8734 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DMATX_BUILD_DOCS=OFF .. && \
    make -j && \
    make install

#
# Install ZeroMQ (socket)
#

RUN apt update && \
    apt install --no-install-recommends -y \
        libzmq3-dev \
        cppzmq-dev \
        && rm -rf /var/lib/apt/lists/*
#
# Install HDF5, FBH5, and UVH5 (filesystem)
#

RUN apt update && \
    apt install --no-install-recommends -y \
        libmpich-dev \
        liberfa-dev \
        && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/HDFGroup/hdf5.git
RUN cd hdf5 && \
    git checkout hdf5-1.14.6 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DHDF5_ENABLE_PARALLEL=NO .. && \
    make -j && \
    make install

RUN git clone https://github.com/hpc-io/vfd-gds.git
RUN cd vfd-gds && \
    git checkout e33bae67a16238c2677f23abac76b9fe30b99869 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_TESTING=OFF .. && \
    make -j && \
    make install

RUN git clone https://github.com/MydonSolutions/filterbankc99.git
RUN cd filterbankc99 \
    && git checkout v1.5.0 \
    && git submodule update --init --recursive \
    && CC=gcc-11 meson setup -Dbuildtype=debugoptimized build \
    && cd build \
    && ninja install

RUN git clone https://github.com/MydonSolutions/uvh5c99.git
RUN cd uvh5c99 \
    && git checkout v0.9.0 \
    && git submodule update --init --recursive \
    && CC=gcc-11 meson setup -Dbuildtype=debugoptimized build \
    && cd build \
    && ninja install

#
# Install CyberEther (cyberether)
#

RUN apt update && \
    apt install --no-install-recommends -y \
        libxkbcommon-dev \
        spirv-cross glslang-tools libglfw3-dev \
        libvulkan-dev vulkan-validationlayers \
        python3-yaml \
        libgstreamer1.0-dev gstreamer1.0-libav \
        gstreamer1.0-plugins-base libgstreamer-plugins-bad1.0-dev \
        libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev \
        gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
        libsoapysdr-dev soapysdr-module-rtlsdr soapysdr-module-uhd \
        soapysdr-module-airspy soapysdr-module-lms7 soapysdr-tools \
        && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/luigifcruz/CyberEther.git
RUN cd CyberEther \
    && git checkout 813c33d23905b053912b9fc3c7e26bce49f270a3 \
    && rm -fr build \
    && CC=gcc-11 CXX=g++-11 meson setup -Dbuildtype=debugoptimized build \
    && cd build \
    && ninja \
    && ninja install

#
# Install BLADE (blade)
#

RUN apt update && \
    apt install --no-install-recommends -y \
        libbenchmark-dev libgtest-dev \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir numpy astropy pandas

ENV NVCC_PREPEND_FLAGS='-ccbin g++-11'
RUN git clone https://github.com/luigifcruz/blade.git
RUN cd blade \
    && git checkout v1.1 \
    && git submodule update --init --recursive \
    && rm -fr build \
    && CC=gcc-11 CXX=g++-11 meson setup -Dbuildtype=debugoptimized build \
    && cd build \
    && ninja \
    && ninja install

#
# Install Stelline
#

COPY . ./stelline
RUN cd ./stelline \
    && git submodule update --init --recursive \
    && rm -fr build \
    && meson setup -Dbuildtype=debugoptimized build \
    && cd build \
    && ninja \
    && ninja install
