FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04

ARG DEBIAN_FRONTEND=noninteractive

#
# Global Dependencies
#

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        python3 \
        python3-dev \
        python3-pip \
        python3-pybind11 \
        build-essential \
        pkg-config \
        cmake \
        git \
        g++-11 \
        wget \
        curl \
        gcc-11 \
        ca-certificates \
        libssl-dev \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages --no-cache-dir ninja
RUN python3 -m pip install --break-system-packages --no-cache-dir git+https://github.com/luigifcruz/meson.git@system-includes

#
# Install ANO
#

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        python3-pyelftools \
        libnuma-dev \
        rdma-core \
        ibverbs-providers \
        libibverbs1 \
        libibverbs-dev \
        libnl-3-200 \
        libnl-route-3-200 \
        libnuma1 \
        && rm -rf /var/lib/apt/lists/*

RUN wget -q https://fast.dpdk.org/rel/dpdk-24.11.3.tar.xz && \
    tar xf dpdk-24.11.3.tar.xz && \
    rm -f dpdk-24.11.3.tar.xz && \
    cd dpdk-stable-24.11.3/ && \
    meson build -Dplatform=generic -Dmachine=generic && \
    ninja -C build install && \
    cd / && rm -rf /dpdk-stable-24.11.3

RUN git clone https://github.com/luigifcruz/holoscan-networking.git && \
    cd holoscan-networking && \
    git checkout slim && \
    meson build && \
    cd build && \
    ninja install && \
    cd / && rm -rf /holoscan-networking

#
# Install MatX
#

RUN git clone https://github.com/NVIDIA/MatX.git && \
    cd MatX && \
    git checkout ad55c6b894f0fdef65294858d9561ba31baa8734 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DMATX_BUILD_DOCS=OFF .. && \
    make -j && \
    make install && \
    cd / && rm -rf /MatX

#
# Install HDF5, FBH5, and UVH5
#

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        libmpich-dev \
        liberfa-dev \
        && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/HDFGroup/hdf5.git && \
    cd hdf5 && \
    git checkout hdf5-1.14.6 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DHDF5_ENABLE_PARALLEL=NO .. && \
    make -j && \
    make install && \
    cd / && rm -rf /hdf5

RUN git clone https://github.com/hpc-io/vfd-gds.git && \
    cd vfd-gds && \
    git checkout e33bae67a16238c2677f23abac76b9fe30b99869 && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_TESTING=OFF .. && \
    make -j && \
    make install && \
    cd / && rm -rf /vfd-gds

RUN git clone https://github.com/MydonSolutions/filterbankc99.git && \
    cd filterbankc99 && \
    git checkout v1.5.0 && \
    git submodule update --init --recursive && \
    CC=gcc-11 meson setup -Dbuildtype=debugoptimized build && \
    cd build && \
    ninja install && \
    cd / && rm -rf /filterbankc99

RUN git clone https://github.com/MydonSolutions/uvh5c99.git && \
    cd uvh5c99 && \
    git checkout v0.9.2 && \
    git submodule update --init --recursive && \
    CC=gcc-11 meson setup -Dbuildtype=debugoptimized build && \
    cd build && \
    ninja install && \
    cd / && rm -rf /uvh5c99

#
# Install Rust
#

ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
RUN rustc --version && cargo --version
RUN cargo install cargo-c

#
# Install GStreamer
#

ENV GSTROOT=/opt/gstreamer
ENV LD_LIBRARY_PATH="${GSTROOT}/lib/x86_64-linux-gnu:${GSTROOT}/lib"
ENV PKG_CONFIG_PATH="${GSTROOT}/lib/x86_64-linux-gnu/pkgconfig:${GSTROOT}/lib/pkgconfig"
ENV GST_PLUGIN_PATH="${GSTROOT}/lib/x86_64-linux-gnu/gstreamer-1.0:${GSTROOT}/lib/gstreamer-1.0:/usr/local/lib/gstreamer-1.0"
ENV GI_TYPELIB_PATH="${GSTROOT}/lib/x86_64-linux-gnu/girepository-1.0"
ENV GST_PLUGIN_SCANNER="${GSTROOT}/libexec/gstreamer-1.0/gst-plugin-scanner"
ENV PATH="${GSTROOT}/bin:${PATH}"

RUN apt-get update && apt-get install --no-install-recommends -y \
    avahi-utils \
    bison \
    flex \
    clang \
    libssl-dev \
    libglib2.0-dev \
    liborc-0.4-dev \
    libmount-dev \
    libpcre2-dev \
    libdrm-dev \
    libgbm-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libx11-dev \
    libxv-dev \
    libxext-dev \
    libxfixes-dev \
    libxi-dev \
    libasound2-dev \
    libpulse-dev \
    libwayland-dev \
    wayland-protocols \
    libnice-dev \
    libsoup-3.0-dev \
    libsrtp2-dev \
    libngtcp2-dev \
    libgnutls28-dev \
    libcurl4-openssl-dev \
    libnss-mdns \
    nasm \
    yasm \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch 1.28.1 https://gitlab.freedesktop.org/gstreamer/gstreamer.git /tmp/gstreamer && \
    cd /tmp/gstreamer && \
    meson setup build \
      --prefix=${GSTROOT} \
      -Dbad=enabled \
      -Dugly=enabled \
      -Dgpl=enabled \
      -Dtests=disabled \
      -Dexamples=disabled \
      -Ddevtools=disabled && \
    ninja -C build && \
    ninja -C build install && \
    rm -rf /tmp/gstreamer

RUN git clone --depth 1 https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git /tmp/gst-plugins-rs && \
    cd /tmp/gst-plugins-rs && \
    cargo cinstall -p gst-plugin-webrtc \
      --prefix=${GSTROOT} \
      --libdir=${GSTROOT}/lib/x86_64-linux-gnu && \
    rm -rf /tmp/gst-plugins-rs

#
# Install CyberEther
#

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        libxkbcommon-dev \
        spirv-cross \
        glslang-tools \
        libglfw3-dev \
        libvulkan-dev \
        vulkan-validationlayers \
        python3-yaml \
        libsoapysdr-dev \
        soapysdr-module-rtlsdr \
        soapysdr-module-uhd \
        soapysdr-tools \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages --no-cache-dir numpy mapbox_earcut

RUN git clone https://github.com/luigifcruz/CyberEther.git && \
    cd CyberEther && \
    git checkout feat/stelline-fixes && \
    rm -fr build && \
    CC=gcc-11 CXX=g++-11 meson setup -Dbuildtype=debugoptimized build && \
    cd build && \
    ninja && \
    ninja install && \
    cd / && rm -rf /CyberEther

#
# Install BLADE
#

ENV NVCC_PREPEND_FLAGS='-ccbin g++-11'

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        libbenchmark-dev libgtest-dev \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages --no-cache-dir astropy pandas

RUN git clone https://github.com/luigifcruz/blade.git && \
    cd blade && \
    git checkout v1.1 && \
    git submodule update --init --recursive && \
    rm -fr build && \
    CC=gcc-11 CXX=g++-11 meson setup -Dbuildtype=debugoptimized build && \
    cd build && \
    ninja && \
    ninja install && \
    cd / && rm -rf /blade
